apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/kalem-tenant/devfile-sample-python-basic/devfile-sample-python-basic@sha256:a9b865c35738964d8cf24bd07f6ad8a8db03af97c3ee409853830c0a1e406ad1
        name: my-python
        resources: {}
status: {}
